apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsservico-pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microsservico-pagamento
  template:
    metadata:
      labels:
        app: microsservico-pagamento
    spec:
      containers:
        - name: microsservico-pagamento
          image: angolar/pagamento-ms:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
          volumeMounts:
          - name: microsservico-pagamento-config
            subPath: .env
            mountPath: /go/src/pagamento/.env
          
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: microsservico-pagamento-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: microsservico-pagamento-secret
                  key: RABBITMQ_DEFAULT_PASS

      volumes:
      - name: microsservico-pagamento-config
        configMap:
          name: microsservico-pagamento-config
          items:
            - key: env
              path: .env
